#!/usr/bin/env python3
"""
compare_reviews.py — Analyse a baseline vs contextual Revue review pair.

Usage:
    python3 scripts/compare_reviews.py docs/review-comparisons/REVUE-XX/

Reads baseline.json and contextual.json from the given directory,
produces a structured ANALYSIS.md.
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_findings(path: Path) -> list[dict]:
    """Load all findings from a Revue JSON output file."""
    raw = json.loads(path.read_text())
    findings = []

    # Handle both list-of-file-results and flat findings formats
    if isinstance(raw, list):
        for entry in raw:
            review_text = entry.get("review", "")
            findings.extend(_parse_findings_from_text(review_text))
    elif isinstance(raw, dict):
        for entry in raw.get("results", []):
            findings.extend(_parse_findings_from_text(entry.get("review", "")))

    return findings


def _parse_findings_from_text(text: str) -> list[dict]:
    """Extract findings list from a JSON review response string."""
    if not text:
        return []
    try:
        clean = text.strip()
        if clean.startswith("```"):
            clean = "\n".join(clean.split("\n")[1:])
        if clean.endswith("```"):
            clean = "\n".join(clean.split("\n")[:-1])
        data = json.loads(clean.strip())
        if isinstance(data, list):
            return data
        if isinstance(data, dict):
            if "review" in data and isinstance(data["review"], dict):
                data = data["review"]
            return data.get("findings", [])
    except Exception:
        pass
    return []


def severity_bucket(sev: str) -> str:
    sev = sev.lower()
    if sev in ("high", "critical"):
        return "high_med"
    if sev == "medium":
        return "high_med"
    return "low_info"


def count_severities(findings: list[dict]) -> Counter:
    c: Counter = Counter()
    for f in findings:
        sev = f.get("severity", "info").lower()
        c[sev] += 1
    return c


def fingerprint(f: dict) -> str:
    """Loose fingerprint for deduplication across baseline/contextual."""
    issue = (f.get("issue") or f.get("message") or f.get("title") or "").lower()[:60]
    file_path = (f.get("file_path") or f.get("file") or "").lower()
    return f"{file_path}::{issue}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def analyse(comparison_dir: Path) -> None:
    baseline_path = comparison_dir / "baseline.json"
    contextual_path = comparison_dir / "contextual.json"
    pr_desc_path = comparison_dir / "pr_description.txt"

    if not baseline_path.exists():
        print(f"ERROR: baseline.json not found in {comparison_dir}", file=sys.stderr)
        sys.exit(1)
    if not contextual_path.exists():
        print(f"ERROR: contextual.json not found in {comparison_dir}", file=sys.stderr)
        sys.exit(1)

    baseline = load_findings(baseline_path)
    contextual = load_findings(contextual_path)

    b_counts = count_severities(baseline)
    c_counts = count_severities(contextual)

    b_total = len(baseline)
    c_total = len(contextual)
    b_hm = sum(v for k, v in b_counts.items() if k in ("high", "medium", "critical"))
    c_hm = sum(v for k, v in c_counts.items() if k in ("high", "medium", "critical"))

    delta_total = c_total - b_total
    delta_pct = round((delta_total / b_total * 100) if b_total else 0, 1)

    # Fingerprint-based diff
    b_fps = {fingerprint(f): f for f in baseline}
    c_fps = {fingerprint(f): f for f in contextual}

    suppressed = {fp: f for fp, f in b_fps.items() if fp not in c_fps}
    new_in_ctx  = {fp: f for fp, f in c_fps.items() if fp not in b_fps}
    preserved   = {fp: f for fp, f in b_fps.items() if fp in c_fps}

    ticket = comparison_dir.name
    pr_desc_section = pr_desc_path.read_text() if pr_desc_path.exists() else "(not available)"

    lines = [
        f"# Review Comparison: {ticket}",
        f"**Generated by:** scripts/compare_reviews.py  ",
        f"**Dir:** {comparison_dir}  ",
        "",
        "## Summary",
        "",
        "| Metric | Baseline | Contextual | Delta |",
        "|--------|----------|------------|-------|",
        f"| Total findings | {b_total} | {c_total} | {delta_total:+d} ({delta_pct:+.1f}%) |",
        f"| High/Medium | {b_hm} | {c_hm} | {c_hm - b_hm:+d} |",
        f"| Low/Info | {b_total - b_hm} | {c_total - c_hm} | {(c_total - c_hm) - (b_total - b_hm):+d} |",
        f"| Suppressed by context | — | — | {len(suppressed)} |",
        f"| New in contextual | — | — | {len(new_in_ctx)} |",
        f"| Preserved (both) | — | — | {len(preserved)} |",
        "",
        "---",
        "",
        "## Suppressed by Context (in baseline, not in contextual)",
        "",
        "_These appeared without context. With context they were suppressed._  ",
        "_Review each: true false positive (good suppression) or real issue (regression)?_",
        "",
    ]

    if suppressed:
        for fp, f in suppressed.items():
            sev = f.get("severity", "?")
            issue = f.get("issue") or f.get("message") or f.get("title") or "(no title)"
            file_path = f.get("file_path") or f.get("file") or "?"
            cat = f.get("category") or f.get("type") or ""
            lines.append(f"- **[{sev.upper()}]** `{file_path}` — {issue}" + (f" _{cat}_" if cat else ""))
    else:
        lines.append("_No findings suppressed — context had no effect on this metric._")

    lines += [
        "",
        "---",
        "",
        "## Preserved in Both Reviews",
        "",
        "_These appeared regardless of context — likely real issues._",
        "",
    ]

    if preserved:
        for fp, f in preserved.items():
            sev = f.get("severity", "?")
            issue = f.get("issue") or f.get("message") or f.get("title") or "(no title)"
            file_path = f.get("file_path") or f.get("file") or "?"
            lines.append(f"- **[{sev.upper()}]** `{file_path}` — {issue}")
    else:
        lines.append("_No findings preserved across both runs._")

    lines += [
        "",
        "---",
        "",
        "## New Findings in Contextual (not in baseline)",
        "",
        "_Appeared with context but not without. Verify these are real._",
        "",
    ]

    if new_in_ctx:
        for fp, f in new_in_ctx.items():
            sev = f.get("severity", "?")
            issue = f.get("issue") or f.get("message") or f.get("title") or "(no title)"
            file_path = f.get("file_path") or f.get("file") or "?"
            lines.append(f"- **[{sev.upper()}]** `{file_path}` — {issue}")
    else:
        lines.append("_No new findings introduced by context._")

    lines += [
        "",
        "---",
        "",
        "## Observations & Actions",
        "",
        "_Fill in after reviewing the above. What patterns do you see?_",
        "",
        "- [ ] False positives to add to Out of Scope template?",
        "- [ ] Agent-specific noise patterns?",
        "- [ ] `.revue.yml` `ignore_patterns` candidates?",
        "- [ ] Prompt tuning candidates?",
        "- [ ] Project conventions Revue should always know?",
        "",
        "---",
        "",
        "## PR Description Used",
        "",
        "```",
        pr_desc_section.strip(),
        "```",
    ]

    output_path = comparison_dir / "ANALYSIS.md"
    output_path.write_text("\n".join(lines))
    print(f"✅ Analysis written to {output_path}")
    print(f"   Baseline: {b_total} findings ({b_hm} high/med)")
    print(f"   Contextual: {c_total} findings ({c_hm} high/med)")
    print(f"   Suppressed: {len(suppressed)} | Preserved: {len(preserved)} | New: {len(new_in_ctx)}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 scripts/compare_reviews.py <comparison-dir>", file=sys.stderr)
        sys.exit(1)
    analyse(Path(sys.argv[1]))
