#!/usr/bin/env bash
#
# One-command installer for /revue-local Claude Code skill.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/cbscd/revue/main/scripts/install.sh | bash
#
# Post-MVP distributes via https://revue.sh/install.sh with signed releases.
#
# Design (REVUE-276 / E-P2A-S2):
# 1. Prefers `uv tool install --force revue` (modern pip replacement)
# 2. Falls back to `pipx install --force revue` if uv absent
# 3. Auto-detects Claude Code (~/.claude) and writes slash command shim
# 4. Auto-detects .revue.yml in workspace and reuses it
# 5. Aborts if Claude Code not found

set -euo pipefail

readonly CLAUDE_HOME="${HOME}/.claude"
readonly REVUE_YML=".revue.yml"

# ANSI colour codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No Colour

error() {
  printf "${RED}error:${NC} %s\n" "$@" >&2
  exit 1
}

warn() {
  printf "${YELLOW}warn:${NC} %s\n" "$@" >&2
}

info() {
  printf "${GREEN}✓${NC} %s\n" "$@"
}

# Detect Claude Code presence by checking ~/.claude directory
detect_claude_code() {
  if [[ -d "${CLAUDE_HOME}" ]]; then
    return 0
  fi
  return 1
}

# Detect Claude Code skills directory (create if missing)
ensure_skills_dir() {
  local skills_dir="${CLAUDE_HOME}/skills"
  mkdir -p "$skills_dir"
  echo "$skills_dir"
}

# Detect if uv is available on PATH
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Install revue via uv tool install --force
install_via_uv() {
  info "Found uv — installing revue via 'uv tool install --force revue'"
  uv tool install --force revue
}

# Install revue via pipx install --force
install_via_pipx() {
  info "uv not found — falling back to pipx (install --force revue)"
  pipx install --force revue
}

# Run revue install-skill to copy the bundled skill
install_skill() {
  info "Installing bundled skill..."
  revue install-skill --no-overwrite
}

# Write the Claude Code slash command shim
write_slash_command() {
  local commands_dir="$1"
  local command_file="${commands_dir}/revue-local.md"

  mkdir -p "$commands_dir"

  cat > "$command_file" <<'SLASH_CMD'
---
name: revue-local
description: Multi-agent code review — run locally in Claude Code before committing
---

# /revue-local

Run a multi-agent code review on your current staged diff using Revue, an AI code review tool that runs locally inside Claude Code. No platform APIs, no Anthropic spend — the tool uses your AI model of choice (defaulting to DeepSeek v4-pro).

## Basic usage

Invoke `/revue-local` on your staged changes:

1. Stage your changes: `git add <files>`
2. In Claude Code, run `/revue-local`
3. Review the findings by severity
4. Fix any Critical or High findings before committing

See https://revue.sh/docs for full documentation.
SLASH_CMD

  info "Slash command written to ${command_file}"
}

# Detect existing .revue.yml in workspace, or write a default if missing
handle_revue_yml() {
  local workspace_dir="$1"
  local target="${workspace_dir}/${REVUE_YML}"

  if [[ -f "$target" ]]; then
    info "Found existing ${REVUE_YML} in workspace — reusing configuration"
    return 0
  fi

  cat > "$target" <<'REVUE_YML_DEFAULT'
# Default Revue configuration generated by the installer.
# See https://revue.sh/docs/revue-yml-reference for all options.
version: "1"

ai:
  provider: openrouter
  model: deepseek/deepseek-v4-pro
  api_key_env: REVUE_API_KEY
REVUE_YML_DEFAULT
  info "Wrote default ${REVUE_YML} at ${target}"
}

# Main flow
main() {
  # Step 1: Detect Claude Code
  if ! detect_claude_code; then
    error "Claude Code not detected. Install Claude Code first: https://claude.ai/code"
  fi
  info "Claude Code detected at ${CLAUDE_HOME}"

  # Step 2: Install revue package via uv or pipx
  if command_exists uv; then
    install_via_uv
  elif command_exists pipx; then
    install_via_pipx
  else
    error "Neither 'uv' nor 'pipx' found. Install one: https://docs.astral.sh/uv or https://pipx.pypa.io"
  fi

  # Step 3: Install the bundled skill
  install_skill

  # Step 4: Write slash command shim
  ensure_skills_dir >/dev/null
  write_slash_command "${CLAUDE_HOME}/commands"

  # Step 5: Detect and handle .revue.yml
  handle_revue_yml "$(pwd)"

  # Step 6: Verify installation
  info "Installation complete"
  revue --version
  info "Ready to use: invoke /revue-local in Claude Code"
}

main "$@"
